/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:1505f035-2b07-4581-b0df-1bc9bb54a21c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_FgKsoJODP",
    "aws_user_pools_web_client_id": "skmr9ue5bo2l3be5ni2vm5v63",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://34hsxmcyg5av5cccie3o4wcihi.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nywju72sfzci5h3a3zw77mspvm",
    "aws_user_files_s3_bucket": "amplifyappf47cf5b61f234ab7b06ab3a987e27eb8190843-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
